FROM hexpm/elixir:1.19.5-erlang-28.1-debian-bookworm-20260610

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends build-essential git inotify-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["sh", "-c", "mix local.hex --force && mix local.rebar --force && mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"]
